name: Deploy to Server

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          pm2 restart web-server


  deploy_s:
    runs-on-specific-runner:
      runs-on: artemis-s9-runner
      steps:
        - uses: actions/checkout@v2
        
        - name: run udp-listener
          run: |
            cd udp-listener
            cp ~/env-variables/.env-udp-listener ./.env
            npm install
            sudo pm2 restart udp-listener

        - name: run web-server
          run: |
            cd web-server 
            cp ~/env-variables/.env-web-server ./.env
            npm install
            sudo pm2 restart web-server


      