name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: artemis-juan
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          npm install ejs
          sudo pm2 restart web-server


  deploy_s:
    runs-on: artemis-s9
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          npm install ejs
          sudo pm2 restart web-server

  deploy_e:
    runs-on: artemis-edwin
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          npm install ejs
          sudo pm2 restart web-server

  deploy_m:
    runs-on: artemis-may
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          npm install ejs
          sudo pm2 restart web-server

  deploy_f:
    runs-on: artemis-felipe
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          npm install ejs
          sudo pm2 restart web-server


      