name: Deploy to Server

on:
  push:
    branches: 
      - main
      - test-may
      - test-juan
      - test-s9
      - test-edwin
      - test-felipe

jobs:
  deploy:
    runs-on: artemis-juan
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server
          cp ~/env-variables/.env-web-server ./.env
          npm install
          if [ "${{ github.ref }}" == "refs/heads/test-juan" ]; then
            sudo pm2 restart web-server-test
          else
            sudo pm2 restart web-server
          fi

  deploy_s:
    runs-on: artemis-s9
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          sudo pm2 restart web-server

  deploy_e:
    runs-on: artemis-edwin
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          sudo pm2 restart web-server

  deploy_m:
    runs-on: artemis-may
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          sudo pm2 restart web-server

  deploy_f:
    runs-on: artemis-felipe
    steps:
      - uses: actions/checkout@v2
      
      - name: run udp-listener
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener ./.env
          npm install
          sudo pm2 restart udp-listener

      - name: run web-server
        run: |
          cd web-server 
          cp ~/env-variables/.env-web-server ./.env
          npm install
          sudo pm2 restart web-server


      