name: Deploy Individual Staging

on:
  push:
    branches:
      - juan
      - moixnt
      - edwin
      - jfelipe
      - SamirUwu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment for each user
        id: env
        run: |
          BRANCH="${{ github.ref_name }}"
          if [ "$BRANCH" = "juan" ]; then PORT=3101; NAME=juan;
          elif [ "$BRANCH" = "moixnt" ]; then PORT=3102; NAME=may;
          elif [ "$BRANCH" = "edwin" ]; then PORT=3103; NAME=edwin;
          elif [ "$BRANCH" = "jfelipe" ]; then PORT=3104; NAME=felipe;
          elif [ "$BRANCH" = "SamirUwu" ]; then PORT=3105; NAME=santiago;
          else echo "Rama no válida para staging" && exit 1;
          fi
          echo "port=$PORT" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Setup UDP Listener (shared)
        run: |
          cd udp-listener
          cp ~/env-variables/.env-udp-listener .env
          npm install
          sudo pm2 restart udp-listener

      - name: Setup Web Server (per collaborator)
        run: |
          cd web-server
          cp ~/env-variables/.env-web-server .env
          echo "PORT=${{ steps.env.outputs.port }}" >> .env
          npm install
          sudo pm2 delete web-${{ steps.env.outputs.name }} || true
          sudo pm2 start server.js --name web-${{ steps.env.outputs.name }}
